2018-01-02 23:48:33,605 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 4.00ms
2018-01-02 23:48:39,819 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-02 23:48:39,821 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 26.00ms
2018-01-02 23:50:03,053 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-02 23:50:06,795 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-02 23:50:06,796 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 15.00ms
2018-01-02 23:57:03,065 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'If-None-Match': '"0d695ead8c0438eb75426d79491e4b0a8f8e132a"', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 17, in get
    self.render("index.html", base_url=base_url,pager=pager,order_search_params=order_search_params,token=self.token)
AttributeError: 'HomeHandler' object has no attribute 'token'
2018-01-02 23:57:03,069 - tornado.access - web.py[line:2063] - ERROR - 500 GET / (::1) 6.00ms
2018-01-03 00:01:50,454 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 17, in get
    tokenStr = escape.xhtml_escape(self.xsrf_token);
NameError: global name 'escape' is not defined
2018-01-03 00:01:50,457 - tornado.access - web.py[line:2063] - ERROR - 500 GET / (::1) 6.00ms
2018-01-03 00:06:59,630 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 42, in get
    tokenStr = xsrf_token(self);
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 28, in xsrf_token
    token = binascii.b2a_hex(uuid.uuid4().bytes)
NameError: global name 'binascii' is not defined
2018-01-03 00:06:59,632 - tornado.access - web.py[line:2063] - ERROR - 500 GET / (::1) 5.00ms
2018-01-03 00:17:12,584 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 5.00ms
2018-01-03 00:17:25,309 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:17:25,311 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 11.00ms
2018-01-03 00:18:21,171 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-03 00:18:27,513 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:18:27,513 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 10.00ms
2018-01-03 00:19:45,352 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 5.00ms
2018-01-03 00:19:50,144 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:19:50,145 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 13.00ms
2018-01-03 00:20:22,206 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 7.00ms
2018-01-03 00:20:26,780 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:20:26,780 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 6.00ms
2018-01-03 00:21:38,124 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 7.00ms
2018-01-03 00:22:17,792 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:22:17,793 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 290.00ms
2018-01-03 00:24:38,601 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 4.00ms
2018-01-03 00:24:45,367 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:24:45,368 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 10.00ms
2018-01-03 00:26:00,517 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 8.00ms
2018-01-03 00:26:02,249 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '190', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cache-Control': 'max-age=0', 'Cookie': '_xsrf=2|1ba614f1|5d772d63889c67fd512386d632ab6f6b|1514910268', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundarymxdOPgadqPc5KXJi'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 59, in post
    upload_path = os.path.join(os.path.dirname(__file__), 'files')  # 文件的暂存路径
NameError: global name 'os' is not defined
2018-01-03 00:26:02,252 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 6.00ms
2018-01-03 00:27:06,854 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 5.00ms
2018-01-03 00:27:16,796 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-03 00:27:31,308 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:27:31,309 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 9.00ms
2018-01-03 00:28:45,387 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-03 00:30:04,029 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-03 00:30:13,148 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:30:13,150 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 12.00ms
2018-01-03 00:31:04,948 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 5.00ms
2018-01-03 00:31:09,921 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:31:09,923 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 9.00ms
2018-01-03 00:32:29,759 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-03 00:32:41,762 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:32:41,763 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 2.00ms
2018-01-03 00:32:43,099 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:32:43,101 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 2.00ms
2018-01-03 00:32:43,749 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:32:43,750 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 3.00ms
2018-01-03 00:32:44,164 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:32:44,165 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 3.00ms
2018-01-03 00:32:44,732 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:32:44,733 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 3.00ms
2018-01-03 00:32:45,368 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:32:45,369 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 2.00ms
2018-01-03 00:32:46,036 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:32:46,038 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 2.00ms
2018-01-03 00:34:55,365 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-03 00:35:11,618 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-03 00:35:15,413 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:35:15,413 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 1.00ms
2018-01-03 00:36:40,381 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-03 00:36:41,989 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:36:41,990 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 2.00ms
2018-01-03 00:36:42,855 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:36:42,857 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 2.00ms
2018-01-03 00:36:43,621 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:36:43,622 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 3.00ms
2018-01-03 00:36:44,085 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:36:44,086 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 3.00ms
2018-01-03 00:36:44,339 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:36:44,339 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 1.00ms
2018-01-03 00:36:44,772 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:36:44,773 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 3.00ms
2018-01-03 00:36:44,951 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:36:44,953 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 3.00ms
2018-01-03 00:36:45,134 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:36:45,137 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 3.00ms
2018-01-03 00:36:45,299 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:36:45,302 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 3.00ms
2018-01-03 00:36:45,460 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:36:45,463 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 3.00ms
2018-01-03 00:36:45,625 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:36:45,628 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 3.00ms
2018-01-03 00:36:45,796 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:36:45,799 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 2.00ms
2018-01-03 00:36:45,957 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:36:45,959 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 3.00ms
2018-01-03 00:36:46,108 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:36:46,111 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 3.00ms
2018-01-03 00:36:46,273 - tornado.general - web.py[line:1587] - WARNING - 403 POST / (::1): '_xsrf' argument missing from POST
2018-01-03 00:36:46,276 - tornado.access - web.py[line:2063] - WARNING - 403 POST / (::1) 3.00ms
2018-01-03 00:37:27,210 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 8.00ms
2018-01-03 00:37:29,706 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '190', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cache-Control': 'max-age=0', 'Cookie': '_xsrf=2|1ba614f1|5d772d63889c67fd512386d632ab6f6b|1514910268', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryeFG5eb5n4U8ThFKR'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1143, in handle_yield
    self.future = convert_yielded(yielded)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1277, in convert_yielded
    return multi(yielded)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 721, in multi
    return multi_future(children, quiet_exceptions=quiet_exceptions)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 814, in multi_future
    children = list(map(convert_yielded, children))
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1283, in convert_yielded
    raise BadYieldError("yielded unknown object %r" % (yielded,))
BadYieldError: yielded unknown object 'Invalid Args'
2018-01-03 00:37:29,707 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 53.00ms
2018-01-03 00:38:42,851 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-03 00:38:57,650 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 7.00ms
2018-01-03 00:39:18,138 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 3.00ms
2018-01-03 00:40:12,937 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 1.00ms
2018-01-03 00:40:14,671 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-03 00:40:19,805 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '459452', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cache-Control': 'max-age=0', 'Cookie': '_xsrf=2|1ba614f1|5d772d63889c67fd512386d632ab6f6b|1514910268', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundarywjCisee8b6C7Y7yE'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 72, in post
    with open(file_path, 'wb') as up:
IOError: [Errno 2] No such file or directory: u'E:\\pythonFile\\pythonProgram\\pythonSrc\\srcReal\\controller\\files\\12.8\u53f7\u8ba2\u5355\u6d41\u6c34\u5e10.xlsx'
2018-01-03 00:40:19,805 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 18.00ms
2018-01-03 00:42:07,615 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 3.00ms
2018-01-03 00:42:09,002 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-03 00:42:14,838 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '503618', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cache-Control': 'max-age=0', 'Cookie': '_xsrf=2|1ba614f1|5d772d63889c67fd512386d632ab6f6b|1514910268', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryAsNY1bXZmSr0qvq3'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 76, in post
    self.write(json.dumps(ret))
NameError: global name 'json' is not defined
2018-01-03 00:42:14,839 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 34.00ms
2018-01-03 00:44:59,756 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 7.00ms
2018-01-03 00:45:01,217 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-03 21:34:27,770 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 16.00ms
2018-01-03 22:00:49,332 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '503618', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cache-Control': 'max-age=0', 'Cookie': '_xsrf=2|cb92a1a0|fbff1f2467fa4b8dcdbf7dd9e68507ed|1514987401', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundarydFHOgKz9TK2iiAxb'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 95, in post
    alllines.push(line)
AttributeError: 'list' object has no attribute 'push'
2018-01-03 22:00:49,335 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 3749.00ms
2018-01-03 22:06:27,289 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '503618', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cache-Control': 'max-age=0', 'Cookie': '_xsrf=2|cb92a1a0|fbff1f2467fa4b8dcdbf7dd9e68507ed|1514987401', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryvBl0cAhvcnS6caE9'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 93, in post
    for rownum in range(1, ws.nrows):
AttributeError: 'Worksheet' object has no attribute 'nrows'
2018-01-03 22:06:27,292 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 3948.00ms
2018-01-03 22:11:35,763 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (127.0.0.1) 4.00ms
2018-01-03 22:11:35,924 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (127.0.0.1) 6.00ms
2018-01-03 22:11:45,365 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '503618', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cache-Control': 'max-age=0', 'Cookie': '_xsrf=2|cb92a1a0|fbff1f2467fa4b8dcdbf7dd9e68507ed|1514987401', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundarydXJ64scSdKXVC6BO'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 108, in post
    respon_json = tornado.escape.json_decode(ret)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\escape.py", line 87, in json_decode
    return json.loads(to_basestring(value))
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\escape.py", line 248, in to_basestring
    "Expected bytes, unicode, or None; got %r" % type(value)
TypeError: Expected bytes, unicode, or None; got <type 'dict'>
2018-01-03 22:11:45,371 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (127.0.0.1) 3848.00ms
2018-01-03 22:12:37,161 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (127.0.0.1) 3.00ms
2018-01-03 22:12:37,316 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (127.0.0.1) 5.00ms
2018-01-03 22:12:50,950 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '503618', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cache-Control': 'max-age=0', 'Cookie': '_xsrf=2|cb92a1a0|fbff1f2467fa4b8dcdbf7dd9e68507ed|1514987401', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundarymTySWBVWjvyhcSqx'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 109, in post
    self.render("index.html",respon_json=respon_json)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 724, in render
    html = self.render_string(template_name, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 865, in render_string
    return t.generate(**namespace)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\template.py", line 348, in generate
    return execute()
  File "index_html.generated.py", line 32, in _tt_execute
    _tt_tmp = _tt_modules.Template("_macros.html", pager=pager, url=base_url, params=order_search_params.to_url_params())  # index.html:74 (via base.html:22, base.html:20)
NameError: global name 'pager' is not defined
2018-01-03 22:12:50,957 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (127.0.0.1) 3728.00ms
2018-01-03 22:13:35,622 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 5.00ms
2018-01-03 22:13:35,891 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-03 22:13:44,278 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '503618', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cache-Control': 'max-age=0', 'Cookie': '_xsrf=2|cb92a1a0|fbff1f2467fa4b8dcdbf7dd9e68507ed|1514987401', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryGrBtpo701fOaVh9L'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 111, in post
    self.render("index.html", base_url=base_url,pager=pager,respon_json=respon_json)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 724, in render
    html = self.render_string(template_name, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 865, in render_string
    return t.generate(**namespace)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\template.py", line 348, in generate
    return execute()
  File "index_html.generated.py", line 32, in _tt_execute
    _tt_tmp = _tt_modules.Template("_macros.html", pager=pager, url=base_url, params=order_search_params.to_url_params())  # index.html:74 (via base.html:22, base.html:20)
NameError: global name 'order_search_params' is not defined
2018-01-03 22:13:44,280 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 3691.00ms
2018-01-03 22:14:25,174 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 5.00ms
2018-01-03 22:14:25,312 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 5.00ms
2018-01-03 22:14:32,960 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '503618', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cache-Control': 'max-age=0', 'Cookie': '_xsrf=2|cb92a1a0|fbff1f2467fa4b8dcdbf7dd9e68507ed|1514987401', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryts6Ndli7fsqn4I04'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 113, in post
    self.write(respon_json)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 708, in write
    raise RuntimeError("Cannot write() after finish()")
RuntimeError: Cannot write() after finish()
2018-01-03 22:14:33,071 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 2.00ms
2018-01-03 22:15:51,186 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 3.00ms
2018-01-03 22:15:52,608 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': '_xsrf=2|cb92a1a0|fbff1f2467fa4b8dcdbf7dd9e68507ed|1514987401', 'Cache-Control': 'max-age=0', 'If-None-Match': '"1fcbd452ff7641246c3429e079612f2a7a2b0a3d"', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 20, in get
    self.render("index.html", base_url=base_url,pager=pager,order_search_params=order_search_params)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 724, in render
    html = self.render_string(template_name, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 862, in render_string
    t = loader.load(template_name)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\template.py", line 427, in load
    self.templates[name] = self._create_template(name)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\template.py", line 455, in _create_template
    template = Template(f.read(), name=name, loader=self)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\template.py", line 306, in __init__
    self.file = _File(self, _parse(reader, self))
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\template.py", line 955, in _parse
    block_body = _parse(reader, template, operator, in_loop)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\template.py", line 978, in _parse
    reader.raise_parse_error("unknown operator: %r" % operator)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\template.py", line 788, in raise_parse_error
    raise ParseError(msg, self.name, self.line)
ParseError: unknown operator: 'respon_json' at index.html:11
2018-01-03 22:15:52,611 - tornado.access - web.py[line:2063] - ERROR - 500 GET / (::1) 9.00ms
2018-01-03 22:15:54,480 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': '_xsrf=2|cb92a1a0|fbff1f2467fa4b8dcdbf7dd9e68507ed|1514987401', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 20, in get
    self.render("index.html", base_url=base_url,pager=pager,order_search_params=order_search_params)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 724, in render
    html = self.render_string(template_name, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 862, in render_string
    t = loader.load(template_name)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\template.py", line 427, in load
    self.templates[name] = self._create_template(name)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\template.py", line 455, in _create_template
    template = Template(f.read(), name=name, loader=self)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\template.py", line 306, in __init__
    self.file = _File(self, _parse(reader, self))
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\template.py", line 955, in _parse
    block_body = _parse(reader, template, operator, in_loop)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\template.py", line 978, in _parse
    reader.raise_parse_error("unknown operator: %r" % operator)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\template.py", line 788, in raise_parse_error
    raise ParseError(msg, self.name, self.line)
ParseError: unknown operator: 'respon_json' at index.html:11
2018-01-03 22:15:54,483 - tornado.access - web.py[line:2063] - ERROR - 500 GET / (::1) 4.00ms
2018-01-03 22:23:09,214 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 5.00ms
2018-01-03 22:23:34,687 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-03 22:31:32,115 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-03 22:31:46,404 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '503618', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cookie': '_xsrf=2|cb92a1a0|fbff1f2467fa4b8dcdbf7dd9e68507ed|1514987401', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryQmSixBFXvf66eX5O'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 113, in post
    self.write(respon_json)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 708, in write
    raise RuntimeError("Cannot write() after finish()")
RuntimeError: Cannot write() after finish()
2018-01-03 22:33:05,292 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 4.00ms
2018-01-03 22:46:53,141 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-03 22:47:07,357 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '503618', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cookie': '_xsrf=2|cb92a1a0|fbff1f2467fa4b8dcdbf7dd9e68507ed|1514987401', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryVjGpMfBWYgsAvUXg'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 88, in post
    ws_rows_len = len(ws.rows)          #行数
TypeError: object of type 'generator' has no len()
2018-01-03 22:47:07,358 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 3754.00ms
2018-01-03 22:47:36,641 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (127.0.0.1) 4.00ms
2018-01-03 22:47:47,476 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '503618', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cookie': '_xsrf=2|cb92a1a0|fbff1f2467fa4b8dcdbf7dd9e68507ed|1514987401', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryUpt7cZGFzK6mPDIZ'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 88, in post
    ws_rows_len = len(ws.rows)          #行数
TypeError: object of type 'generator' has no len()
2018-01-03 22:47:47,476 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (127.0.0.1) 3770.00ms
2018-01-03 22:49:13,385 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 7.00ms
2018-01-03 22:49:24,908 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '503618', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cookie': '_xsrf=2|cb92a1a0|fbff1f2467fa4b8dcdbf7dd9e68507ed|1514987401', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundarywsI8o1wsKCNWaMyQ'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 88, in post
    ws_rows_len = len(ws.rows)          #行数
TypeError: object of type 'generator' has no len()
2018-01-03 22:49:24,910 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 3630.00ms
2018-01-03 23:43:38,200 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-04 00:00:11,809 - tornado.application - concurrent.py[line:129] - ERROR - Future exception was never retrieved: Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\service\init_service.py", line 35, in flush_all_cache
    yield cache_manager.call("DEL", *get_all_site_cache_keys())
NameError: global name 'get_all_site_cache_keys' is not defined
2018-01-04 00:00:47,740 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 5.00ms
2018-01-04 00:04:42,690 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 7.00ms
2018-01-04 00:09:03,829 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-04 00:14:15,056 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 5.00ms
2018-01-04 23:02:23,023 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '516158', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cookie': '_xsrf=2|a350197a|f23dabe106da97d01186c9f2799d6a9e|1515069837', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryOgeXN9H1zafDHG0z'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 80, in post
    wb = load_workbook(file_path,data_only=True)  #加载一个工作簿
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\openpyxl\reader\excel.py", line 171, in load_workbook
    archive = _validate_archive(filename)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\openpyxl\reader\excel.py", line 118, in _validate_archive
    archive = ZipFile(filename, 'r', ZIP_DEFLATED)
  File "c:\python27\Lib\zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: u'E:\\pythonFile\\pythonProgram\\pythonSrc\\srcReal\\controller\\files\\12.9\u53f7\u8ba2\u5355\u6d41\u6c34\u5e10.xlsx'
2018-01-04 23:02:23,039 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 84.00ms
2018-01-04 23:02:47,437 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 3.00ms
2018-01-04 23:03:00,555 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 5.00ms
2018-01-04 23:03:06,753 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '516158', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cookie': '_xsrf=2|a350197a|f23dabe106da97d01186c9f2799d6a9e|1515069837', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryaSW8cAXDDKf0vtkz'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 80, in post
    wb = load_workbook(file_path,data_only=True)  #加载一个工作簿
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\openpyxl\reader\excel.py", line 171, in load_workbook
    archive = _validate_archive(filename)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\openpyxl\reader\excel.py", line 118, in _validate_archive
    archive = ZipFile(filename, 'r', ZIP_DEFLATED)
  File "c:\python27\Lib\zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: u'E:\\pythonFile\\pythonProgram\\pythonSrc\\srcReal\\controller\\files\\12.9\u53f7\u8ba2\u5355\u6d41\u6c34\u5e10.xlsx'
2018-01-04 23:03:06,769 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 31.00ms
2018-01-04 23:05:13,701 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 5.00ms
2018-01-04 23:05:19,467 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '516158', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cookie': '_xsrf=2|a350197a|f23dabe106da97d01186c9f2799d6a9e|1515069837', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryrZoaDZIT4qrO7E5Q'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 80, in post
    wb = load_workbook(file_path,data_only=True)  #加载一个工作簿
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\openpyxl\reader\excel.py", line 171, in load_workbook
    archive = _validate_archive(filename)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\openpyxl\reader\excel.py", line 118, in _validate_archive
    archive = ZipFile(filename, 'r', ZIP_DEFLATED)
  File "c:\python27\Lib\zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: u'E:\\pythonFile\\pythonProgram\\pythonSrc\\srcReal\\controller\\files\\12.9\u53f7\u8ba2\u5355\u6d41\u6c34\u5e10.xlsx'
2018-01-04 23:05:19,467 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 16.00ms
2018-01-04 23:06:15,653 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '516158', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cookie': '_xsrf=2|a350197a|f23dabe106da97d01186c9f2799d6a9e|1515069837', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryKu5NAVVpAsytuzLk'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 80, in post
    wb = load_workbook(file_path,data_only=True)  #加载一个工作簿
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\openpyxl\reader\excel.py", line 171, in load_workbook
    archive = _validate_archive(filename)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\openpyxl\reader\excel.py", line 118, in _validate_archive
    archive = ZipFile(filename, 'r', ZIP_DEFLATED)
  File "c:\python27\Lib\zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: u'E:\\pythonFile\\pythonProgram\\pythonSrc\\srcReal\\controller\\files\\12.9\u53f7\u8ba2\u5355\u6d41\u6c34\u5e10.xlsx'
2018-01-04 23:06:15,657 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 4350.00ms
2018-01-04 23:07:32,282 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 5.00ms
2018-01-04 23:07:38,210 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '516158', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cookie': '_xsrf=2|a350197a|f23dabe106da97d01186c9f2799d6a9e|1515069837', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryAPEPIHT5mHT51ogI'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 80, in post
    wb = load_workbook(file_path,data_only=True)  #加载一个工作簿
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\openpyxl\reader\excel.py", line 171, in load_workbook
    archive = _validate_archive(filename)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\openpyxl\reader\excel.py", line 118, in _validate_archive
    archive = ZipFile(filename, 'r', ZIP_DEFLATED)
  File "c:\python27\Lib\zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: u'E:\\pythonFile\\pythonProgram\\pythonSrc\\srcReal\\controller\\files\\12.9\u53f7\u8ba2\u5355\u6d41\u6c34\u5e10.xlsx'
2018-01-04 23:07:38,226 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 16.00ms
2018-01-04 23:09:59,578 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '516158', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cookie': '_xsrf=2|a350197a|f23dabe106da97d01186c9f2799d6a9e|1515069837', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundarySMNlbSidu0Ll2fGW'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 72, in post
    filename = meta['fileName']
KeyError: 'fileName'
2018-01-04 23:09:59,596 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 34.00ms
2018-01-04 23:13:54,499 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '516158', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cookie': '_xsrf=2|a350197a|f23dabe106da97d01186c9f2799d6a9e|1515069837', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryxK4L01X4LfLwnSET'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 80, in post
    wb = load_workbook(file_path,data_only=True)  #加载一个工作簿
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\openpyxl\reader\excel.py", line 171, in load_workbook
    archive = _validate_archive(filename)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\openpyxl\reader\excel.py", line 118, in _validate_archive
    archive = ZipFile(filename, 'r', ZIP_DEFLATED)
  File "c:\python27\Lib\zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: u'E:\\pythonFile\\pythonProgram\\pythonSrc\\srcReal\\controller\\files\\12.9\u53f7\u8ba2\u5355\u6d41\u6c34\u5e10.xlsx'
2018-01-04 23:13:54,515 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 4456.00ms
2018-01-04 23:15:13,401 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-04 23:15:19,490 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '516158', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cookie': '_xsrf=2|a350197a|f23dabe106da97d01186c9f2799d6a9e|1515069837', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryWZAD8ifxEbNTZB87'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 78, in post
    wb = load_workbook(file_path,data_only=True)  #加载一个工作簿
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\openpyxl\reader\excel.py", line 171, in load_workbook
    archive = _validate_archive(filename)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\openpyxl\reader\excel.py", line 118, in _validate_archive
    archive = ZipFile(filename, 'r', ZIP_DEFLATED)
  File "c:\python27\Lib\zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: u'E:\\pythonFile\\pythonProgram\\pythonSrc\\srcReal\\controller\\files\\12.9\u53f7\u8ba2\u5355\u6d41\u6c34\u5e10.xlsx'
2018-01-04 23:15:19,492 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 15.00ms
2018-01-04 23:18:45,503 - tornado.application - web.py[line:1590] - ERROR - Uncaught exception POST /file/upload (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/file/upload', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Content-Length': '459452', 'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/', 'Cookie': '_xsrf=2|a350197a|f23dabe106da97d01186c9f2799d6a9e|1515069837', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryNVB2RSDHLfbGIJrl'})
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "E:\pythonFile\pythonProgram\pythonSrc\srcReal\controller\home.py", line 78, in post
    wb = load_workbook(file_path,data_only=True)  #加载一个工作簿
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\openpyxl\reader\excel.py", line 171, in load_workbook
    archive = _validate_archive(filename)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\openpyxl\reader\excel.py", line 118, in _validate_archive
    archive = ZipFile(filename, 'r', ZIP_DEFLATED)
  File "c:\python27\Lib\zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: u'E:\\pythonFile\\pythonProgram\\pythonSrc\\srcReal\\controller\\files\\12.8\u53f7\u8ba2\u5355\u6d41\u6c34\u5e10.xlsx'
2018-01-04 23:18:45,505 - tornado.access - web.py[line:2063] - ERROR - 500 POST /file/upload (::1) 18.00ms
2018-01-04 23:20:29,361 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-04 23:22:35,493 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-04 23:36:10,943 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-04 23:47:42,522 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 5.00ms
2018-01-04 23:52:09,545 - tornado.access - web.py[line:2063] - WARNING - 404 GET /static/css/bootstrap.css.map (::1) 6.00ms
2018-01-04 23:58:52,285 - sqlalchemy.pool.QueuePool - pool.py[line:643] - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\sqlalchemy\pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\sqlalchemy\pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "E:\pythonFile\pythonProgram\pythonSrc\venu\lib\site-packages\sqlalchemy\dialects\mysql\base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2013, 'Lost connection to MySQL server during query')
